### ISSUE TITLE
viikko3 katselmointi

### ISSUE THREAD

**Issue by raarh** [mknn/Tsoha-Bootstrap#1]
Koodi näytti kivalta ja ei ole valittamista sen osalta. Myös sivun toiminnot näytti toimivan. 

Käytettävyyttä voisi etusivun osalta vähän kehittää. Minulle ei ollut kauhean intuitiivista suorittaa umpimähkään hakua drinkkeihin. Olisi kiva jos sivu vihjaisi käyttäjää jotenkin, mitä hakukenttään tulisi syöttää. Lisäksi haku voisi toimia käyttäjän kannalta kivemmin, jos haku ei huomioisi kirjainkokoa, eli haut vesi ja VeSi tuottaisi saman tuloksen.

**Comment by mknn** [comment]
Lisätty tooltip hakukenttään sekä muutettu hakua jotta kirjainkoolla ei ole väliä.
